# TCL File Generated by Component Editor 13.0sp1
# Sun Jan 12 21:13:15 GMT+04:00 2014
# DO NOT MODIFY


# 
# fi_mem_connector "fi_mem_connector" v1.0
#  2014.01.12.21:13:15
# Connects array of memory fault injection agents to the [NIOS] processor 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module fi_mem_connector
# 
set_module_property DESCRIPTION "Connects array of memory fault injection agents to the \[NIOS] processor "
set_module_property NAME fi_mem_connector
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME fi_mem_connector
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fi_mem_connector
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file fi_mem_connector.vhd VHDL PATH hdl/fi_mem_connector.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter N INTEGER 4
set_parameter_property N DEFAULT_VALUE 4
set_parameter_property N DISPLAY_NAME N
set_parameter_property N TYPE INTEGER
set_parameter_property N UNITS None
set_parameter_property N ALLOWED_RANGES -2147483648:2147483647
set_parameter_property N HDL_PARAMETER true
add_parameter iw INTEGER 2
set_parameter_property iw DEFAULT_VALUE 2
set_parameter_property iw DISPLAY_NAME iw
set_parameter_property iw TYPE INTEGER
set_parameter_property iw UNITS None
set_parameter_property iw ALLOWED_RANGES -2147483648:2147483647
set_parameter_property iw HDL_PARAMETER true
add_parameter dw_max INTEGER 8
set_parameter_property dw_max DEFAULT_VALUE 8
set_parameter_property dw_max DISPLAY_NAME dw_max
set_parameter_property dw_max TYPE INTEGER
set_parameter_property dw_max UNITS None
set_parameter_property dw_max ALLOWED_RANGES -2147483648:2147483647
set_parameter_property dw_max HDL_PARAMETER true
add_parameter aw_max INTEGER 5
set_parameter_property aw_max DEFAULT_VALUE 5
set_parameter_property aw_max DISPLAY_NAME aw_max
set_parameter_property aw_max TYPE INTEGER
set_parameter_property aw_max UNITS None
set_parameter_property aw_max ALLOWED_RANGES -2147483648:2147483647
set_parameter_property aw_max HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock_sink
set_interface_property avalon_slave associatedReset reset_sink
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave fi_A_i address Input aw_max+iw
add_interface_port avalon_slave fi_Mask_i writedata Input dw_max
add_interface_port avalon_slave fi_data_r_i readdata Output dw_max
add_interface_port avalon_slave fi_ack_i waitrequest_n Output 1
add_interface_port avalon_slave fi_wr_i write Input 1
add_interface_port avalon_slave fi_i chipselect Input 1
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock_sink
set_interface_property conduit_end associatedReset reset_sink
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end fi_ack_o export Input n
add_interface_port conduit_end fi_data_r_o export Input dw_max*n
add_interface_port conduit_end fi_Mask_o export Output dw_max
add_interface_port conduit_end fi_A_o export Output aw_max
add_interface_port conduit_end fi_wr_o export Output 1
add_interface_port conduit_end fi_o export Output n
add_interface_port conduit_end clk_o export Output 1
add_interface_port conduit_end rst_o export Output 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk_i clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_i reset_n Input 1

